# -*- coding: utf-8 -*-
"""Generates app_tr.arb + app_en.arb. The table below is the single source.
Turkish is the template language (the one the app was written in); English is
the translation."""
import json, collections

# key: (tr, en, {placeholder: type}) — a type of None means no placeholders
K = collections.OrderedDict()
def k(name, tr, en, ph=None, desc=None):
    K[name] = (tr, en, ph, desc)

# ---------------- common ----------------
k('commonRefresh', 'Yenile', 'Refresh')
k('commonCancel', 'Vazgeç', 'Cancel')
k('commonClose', 'Kapat', 'Close')
k('commonSave', 'Kaydet', 'Save')
k('commonDelete', 'Sil', 'Delete')
k('commonCreate', 'Oluştur', 'Create')
k('commonApply', 'Uygula', 'Apply')
k('commonLoading', 'Yükleniyor', 'Loading')
k('commonCopied', 'Kopyalandı', 'Copied')
k('commonAll', 'Tümü', 'All')
k('commonNoRecords', 'Kayıt yok.', 'No records.')
k('commonNoData', 'Veri yok.', 'No data.')
k('commonAnonymous', 'anonim', 'anonymous')
k('commonError', 'Hata', 'Error')
k('commonOwner', 'sahip', 'owner')
k('commonMember', 'üye', 'member')
k('commonOpen', 'açık', 'open')
k('commonResolved', 'çözüldü', 'resolved')
k('commonEnded', 'bitti', 'ended')
k('commonEmpty', '—', '—', None, 'The no-value marker; the same dash in every language')

# ---------------- error texts (keyed on the backend `code` field) ----------------
k('errNetwork', 'Sunucuya ulaşılamıyor ({endpoint}).', 'Cannot reach the server ({endpoint}).', {'endpoint': 'String'})
k('errInvalidCredentials', 'E-posta veya şifre hatalı.', 'Wrong email or password.')
k('errSessionExpired', 'Oturum geçersiz; yeniden giriş yapın.', 'Your session has expired, please sign in again.')
k('errOwnerRequired', 'Bu işlem için proje sahibi olmalısınız.', 'You must be the project owner to do that.')
k('errNotFound', 'Bulunamadı.', 'Not found.')
k('errEmailTaken', 'Bu e-posta zaten kayıtlı.', 'That email address is already registered.')
k('errPasswordTooShort', 'Şifre en az 6 karakter olmalı.', 'The password must be at least 6 characters.')
k('errInvalidEmail', 'Geçerli bir e-posta girin.', 'Enter a valid email address.')
k('errUnknownMember', 'Bu e-postayla kayıtlı kullanıcı yok; önce kayıt olmalı.', 'Nobody is registered with that email address; they must sign up first.')
k('errSelfRemove', 'Kendinizi projeden çıkaramazsınız.', 'You cannot remove yourself from the project.')
k('errProjectNameRequired', 'Proje adı gerekli.', 'A project name is required.')
k('errUnsupportedLocale', 'Bu dil desteklenmiyor.', 'That language is not supported.')
k('errAlertChannelInvalid', 'Geçersiz bildirim kanalı bilgisi.', 'Invalid notification channel details.')
k('errAlertRuleInvalid', 'Geçersiz uyarı kuralı bilgisi.', 'Invalid alert rule details.')
k('errAlertSendFailed', 'Bildirim gönderilemedi.', 'Failed to send alert notification.')

# ---------------- formatting ----------------
k('fmtJustNow', 'az önce', 'just now')
k('fmtMinutesAgo', '{count} dk önce', '{count, plural, =1{1 minute ago} other{{count} minutes ago}}', {'count': 'int'})
k('fmtHoursAgo', '{count} sa önce', '{count, plural, =1{1 hour ago} other{{count} hours ago}}', {'count': 'int'})
k('fmtDaysAgo', '{count} gün önce', '{count, plural, =1{1 day ago} other{{count} days ago}}', {'count': 'int'})
k('fmtSeconds', '{count} sn', '{count}s', {'count': 'int'})
k('fmtMinutes', '{count} dk', '{count}m', {'count': 'int'})
k('fmtHours', '{hours} sa', '{hours}h', {'hours': 'String'})
k('fmtDateTimePattern', 'dd.MM.yyyy HH:mm', 'MMM d, yyyy HH:mm', None,
  'intl DateFormat pattern — not a translation but how that language writes dates')
k('fmtDayPattern', 'dd MMM', 'MMM dd', None, 'Short day pattern for chart and column labels')
k('fmtClockPattern', 'HH:mm:ss', 'HH:mm:ss', None, 'Clock pattern for the replay player')

# ---------------- shell / navigation ----------------
k('navOverview', 'Genel bakış', 'Overview')
k('navIssues', 'Hatalar', 'Issues')
k('navSessions', 'Oturumlar', 'Sessions')
k('navUsers', 'Kullanıcılar', 'Users')
k('navReleases', 'Sürümler', 'Releases')
k('navEvents', 'Olaylar', 'Events')
k('navSettings', 'Ayarlar', 'Settings')
k('releasesTitle', 'Sürümler', 'Releases')
k('releasesCount', '{count} sürüm', '{count, plural, =1{1 release} other{{count} releases}}', {'count': 'int'})
k('releasesLoadFailed', 'Sürümler alınamadı: {error}', 'Could not load releases: {error}', {'error': 'String'})
k('releasesEmpty', 'Henüz sürüm verisi yok.', 'No release data yet.')
k('colCrashFreeRate', 'Hatasız Oturum %', 'Crash-Free %')
k('colAdoption', 'Kullanım %', 'Adoption %')
k('colErrorSessions', 'Hatalı Oturum', 'Error Sessions')
k('issueReleaseFirst', 'İlk sürüm', 'First release')
k('issueReleaseLast', 'Son sürüm', 'Last release')
k('issueReleaseResolvedIn', 'Çözüldüğü sürüm', 'Resolved in release')
k('shellSourceTooltip', 'Kaynak kodu: {url}', 'Source code: {url}', {'url': 'String'})

k('shellSignOut', 'Çıkış', 'Sign out')
k('shellLanguage', 'Dil', 'Language')
k('languageTurkish', 'Türkçe', 'Türkçe', None, 'A language name is written in its own language')
k('languageEnglish', 'English', 'English', None, 'A language name is written in its own language')

# ---------------- sign in / sign up ----------------
k('authSignIn', 'Giriş yap', 'Sign in')
k('authSignInSubtitle', 'sightpane panosuna hesabınızla devam edin.', 'Continue to the sightpane dashboard with your account.')
k('authNoAccount', 'Hesabınız yok mu?', 'No account yet?')
k('authGoRegister', 'Kayıt olun', 'Sign up')
k('authRegisterTitle', 'Hesap oluştur', 'Create an account')
k('authRegisterSubtitle', 'Kayıt olun, ilk projenizi açın, anahtarınızı SDK’ya verin.', 'Sign up, create your first project, hand the key to the SDK.')
k('authHaveAccount', 'Zaten hesabınız var mı?', 'Already have an account?')
k('authGoSignIn', 'Giriş yapın', 'Sign in')
k('authRegister', 'Kayıt ol', 'Sign up')
k('authEmail', 'E-posta', 'Email')
k('authEmailHint', 'ad@sirket.com', 'name@company.com')
k('authPassword', 'Şifre', 'Password')
k('authPasswordRepeat', 'Şifre (tekrar)', 'Password (again)')
k('authFullName', 'Ad Soyad', 'Full name')
k('authFullNameHint', 'Ayşe Yılmaz', 'Jane Doe')
k('authPasswordHint', 'en az 6 karakter', 'at least 6 characters')
k('authInvalidEmail', 'Geçerli bir e-posta girin', 'Enter a valid email address')
k('authPasswordRequired', 'Şifre gerekli', 'A password is required')
k('authPasswordTooShort', 'Şifre en az 6 karakter olmalı', 'The password must be at least 6 characters')
k('authPasswordMismatch', 'Şifreler eşleşmiyor', 'The passwords do not match')

# ---------------- projects ----------------
k('projectsTitle', 'Projeler', 'Projects')
k('projectsCount', '{count} proje', '{count, plural, =1{1 project} other{{count} projects}}', {'count': 'int'})
k('projectsNew', 'Yeni proje', 'New project')
k('projectsLoading', 'Projeler yükleniyor', 'Loading projects')
k('projectsLoadFailed', 'Projeler alınamadı: {error}', 'Could not load projects: {error}', {'error': 'String'})
k('projectsEmptyTitle', 'Henüz projeniz yok.', 'You have no projects yet.')
k('projectsEmptyBody', 'Bir proje açın; anahtarını ve adresini SDK’ya verin.', 'Create a project, then hand its key and address to the SDK.')
k('projectsCreateFirst', 'İlk projeyi oluştur', 'Create the first project')
k('projectKeyAndAge', 'anahtar {key} · {age}', 'key {key} · {age}', {'key': 'String', 'age': 'String'})
k('projectStatSessions24h', 'Oturum 24s', 'Sessions 24h')
k('projectStatErrors24h', 'Hata 24s', 'Errors 24h')
k('projectStatOpenIssues', 'Açık grup', 'Open groups')
k('projectCreated', '{name} oluşturuldu', '{name} created', {'name': 'String'})
k('projectGoTo', 'Projeye git', 'Go to project')
k('projectName', 'Proje adı', 'Project name')
k('projectNameRequired', 'Proje adı gerekli', 'A project name is required', None,
  'Inline form warning, no full stop — errProjectNameRequired is the server error')
k('projectNameHint', 'Kasa uygulaması', 'Checkout app')
k('projectPlatform', 'Platform', 'Platform')
k('setupAddress', 'Adres', 'Address')
k('setupApiKey', 'API anahtarı', 'API key')
k('setupTitle', 'Kurulum', 'Setup')

# ---------------- overview ----------------
k('overviewSubtitle', 'son {days} gün', 'last {days} days', {'days': 'int'})
k('overviewDaysShort', '{days} g', '{days}d', {'days': 'int'})
k('overviewStatsLoading', 'İstatistikler yükleniyor', 'Loading statistics')
k('overviewStatsFailed', 'İstatistikler alınamadı: {error}', 'Could not load statistics: {error}', {'error': 'String'})
k('overviewSessionsAndErrors', 'Oturumlar ve hatalar', 'Sessions and errors')
k('overviewSessionsAndErrorsNote', 'gün bazında · amber oturum, kırmızı hata', 'by day · amber sessions, red errors')
k('overviewEvents', 'Olaylar', 'Events')
k('overviewByDay', 'gün bazında', 'by day')
k('overviewTopIssues', 'En sık hatalar', 'Most frequent errors')
k('overviewNoOpenIssues', 'Açık hata yok.', 'No open errors.')
k('overviewPlatforms', 'Platformlar', 'Platforms')
k('overviewReleases', 'Sürümler', 'Releases')
k('overviewTopEvents', 'En sık olaylar', 'Most frequent events')
k('kpiSessions', 'Oturum', 'Sessions')
k('kpiVisitorsNote', '{count} ziyaretçi (kullanıcı + IP + tarayıcı)', '{count} visitors (user + IP + browser)', {'count': 'String'})
k('kpiErrors', 'Hata', 'Errors')
k('kpiOpenGroupsNote', '{count} açık grup', '{count} open groups', {'count': 'String'})
k('kpiCrashFree', 'Hatasız oturum', 'Crash-free sessions')
k('kpiEvents', 'Olay', 'Events')
k('kpiFramesNote', '{count} kayıt karesi', '{count} replay frames', {'count': 'String'})
k('livePages', 'Sayfalar', 'Pages')
k('liveRouteCount', '{count} rota', '{count, plural, =1{1 route} other{{count} routes}}', {'count': 'int'})
k('liveNoPages', 'Şu anda görüntülenen sayfa yok.', 'No page is being viewed right now.')
k('liveNoRoute', '(rota yok)', '(no route)')
k('livePeopleCount', '{count} kişi', '{count, plural, =1{1 person} other{{count} people}}', {'count': 'int'})
k('liveViewers', 'Görüntüleyenler', 'Viewers')
k('liveWindow', 'son {seconds} sn', 'last {seconds}s', {'seconds': 'int'})
k('liveNoOpenSessions', 'Açık oturum yok.', 'No open sessions.')
k('liveMore', '+{count} daha', '+{count} more', {'count': 'int'})
k('liveWaiting', 'Canlı veri bekleniyor', 'Waiting for live data')
k('liveSummary', '{people} kişi şu anda çevrimiçi · {visitors} ziyaretçi', '{people} online right now · {visitors} visitors', {'people': 'int', 'visitors': 'int'})
k('liveRefreshNote', 'saniyede bir yenilenir', 'refreshes every second')

# ---------------- issues ----------------
k('issuesTitle', 'Hatalar', 'Issues')
k('issuesOpenCount', '{count} açık grup', '{count, plural, =1{1 open group} other{{count} open groups}}', {'count': 'int'})
k('issuesShowResolved', 'Çözülenleri göster', 'Show resolved')
k('issuesGroups', 'Hata grupları', 'Error groups')
k('issuesGroupingNote', 'aynı istisna + aynı yığın karesi tek grup', 'same exception + same stack frames means one group')
k('issuesLoadFailed', 'Hatalar alınamadı: {error}', 'Could not load errors: {error}', {'error': 'String'})
k('issuesEmpty', 'Hata yok.', 'No errors.')
k('colError', 'Hata', 'Error')
k('colException', 'İstisna', 'Exception')
k('colCount', 'Sayı', 'Count')
k('colFirst', 'İlk', 'First')
k('colLast', 'Son', 'Last')
k('colStatus', 'Durum', 'Status')
k('issueDetailFailed', 'Hata grubu alınamadı: {error}', 'Could not load the error group: {error}', {'error': 'String'})
k('issueSeenSummary', '{count} kez · ilk {first} · son {last}', '{count} times · first {first} · last {last}', {'count': 'String', 'first': 'String', 'last': 'String'})
k('issueReopen', 'Yeniden aç', 'Reopen')
k('issueResolve', 'Çözüldü', 'Resolve')
k('issueResolvedToast', 'Çözüldü olarak işaretlendi', 'Marked as resolved')
k('issueResolvedToastNote', 'Yeniden görülürse otomatik açılır.', 'It reopens automatically if seen again.')
k('issueAssignee', 'Atanan', 'Assignee')
k('issueUnassigned', 'Atanmamış', 'Unassigned')
k('issueStatus', 'Durum', 'Status')
k('issueStatusOpen', 'Açık', 'Open')
k('issueStatusResolved', 'Çözüldü', 'Resolved')
k('issueStatusIgnored', 'Göz ardı edildi', 'Ignored')
k('issueStatusSnoozed', 'Ertelendi', 'Snoozed')
k('issueActionIgnore', 'Göz ardı et', 'Ignore')
k('issueActionSnooze', 'Ertele', 'Snooze')
k('issueSnoozeTitle', 'Hatayı ertele', 'Snooze issue')
k('issueSnoozeDuration', 'Süreye göre', 'By duration')
k('issueSnooze1Hour', '1 saat', '1 hour')
k('issueSnooze24Hours', '24 saat', '24 hours')
k('issueSnooze7Days', '7 gün', '7 days')
k('issueSnoozeCount', 'Oluşum sayısına göre', 'By occurrence count')
k('issueSnoozeCount10', '10 kez daha olunca', 'After 10 more occurrences')
k('issueSnoozeCount50', '50 kez daha olunca', 'After 50 more occurrences')
k('issueSnoozeCount100', '100 kez daha olunca', 'After 100 more occurrences')
k('issueComments', 'Yorumlar', 'Comments')
k('issueCommentsEmpty', 'Henüz yorum yok.', 'No comments yet.')
k('issueCommentAdd', 'Yorum yaz...', 'Add a comment...')
k('issueCommentSend', 'Gönder', 'Send')
k('issueIgnoredToast', 'Hata göz ardı edildi', 'Issue marked as ignored')
k('issueSnoozedToast', 'Hata ertelendi', 'Issue snoozed')

k('issueStack', 'Yığın', 'Stack trace')
k('issueNoStack', '(yığın yok)', '(no stack trace)')
# A release build's stack is minified JavaScript until a source map is uploaded
# for it; these label the two states and the raw text behind the resolved list.
k('issueStackSymbolicated', 'Kaynak eşlendi', 'Mapped to source')
k('issueStackRaw', 'Ham yığın', 'Raw stack trace')
k('issueStackUnresolved', 'eşlenmedi', 'not mapped')
k('issueStackMinifiedHint', 'Küçültülmüş yapı — bu sürüm için kaynak haritası yükleyin', 'Minified build — upload a source map for this release')
k('issueOccurrences', 'Oluşumlar', 'Occurrences')
k('issueOccurrencesNote', 'son {count}', 'last {count}', {'count': 'int'})
k('colTime', 'Zaman', 'Time')
k('colSession', 'Oturum', 'Session')
k('colRoute', 'Rota', 'Route')
k('colFrame', 'Kare', 'Frame')
k('colMessage', 'Mesaj', 'Message')

# ---------------- sessions ----------------
k('sessionsTitle', 'Oturumlar', 'Sessions')
k('sessionsCount', '{count} oturum', '{count, plural, =1{1 session} other{{count} sessions}}', {'count': 'int'})
k('sessionsUserFilterHint', 'kullanıcı kimliği', 'user id')
k('sessionsOnlyErrors', 'Yalnızca hatalı', 'Only with errors')
k('sessionsRecent', 'Son oturumlar', 'Recent sessions')
k('sessionsLoadFailed', 'Oturumlar alınamadı: {error}', 'Could not load sessions: {error}', {'error': 'String'})
k('sessionsEmpty', 'Bu filtreye uyan oturum yok. SDK bağlıysa birkaç saniye içinde oturumlar burada görünür.', 'No session matches this filter. If the SDK is connected, sessions appear here within seconds.')
k('searchHint', 'Örn: release:1.0 browser:Chrome route:/pay props.plan:pro errors:true', 'e.g. release:1.0 browser:Chrome route:/pay props.plan:pro errors:true')
k('searchFilterQuick', 'Hızlı Filtreler', 'Quick Filters')
k('searchClear', 'Temizle', 'Clear')
k('searchInvalid', 'Arama sorgusu geçersiz: {error}', 'Search query invalid: {error}', {'error': 'String'})
k('searchPlaceholderIssues', 'Hata ara (örn: title:boom resolved:false)', 'Search issues (e.g. title:boom resolved:false)')
k('filterByField', 'ALANA GÖRE FİLTRELE', 'FILTER BY FIELD')
k('filterValues', 'DEĞER SEÇİN', 'SELECT VALUE')
k('filterBrowserDesc', 'Tarayıcıya göre filtrele', 'Filter by browser')
k('filterPlatformDesc', 'Platforma göre filtrele', 'Filter by platform')
k('filterReleaseDesc', 'Sürüme göre filtrele', 'Filter by release version')
k('filterRouteDesc', 'Ekran / rotaya göre filtrele', 'Filter by route')
k('filterUserDesc', 'Kullanıcıya göre filtrele', 'Filter by user ID or email')
k('filterOsDesc', 'İşletim sistemine göre filtrele', 'Filter by operating system')
k('filterErrorsDesc', 'Hata durumuna göre filtrele', 'Filter by error state')
k('filterStatusDesc', 'Duruma göre filtrele', 'Filter by status')
k('filterAssigneeDesc', 'Sorumluya göre filtrele', 'Filter by assignee')
k('filterTitleDesc', 'Başlığa göre filtrele', 'Filter by title')
k('filterExceptionDesc', 'İstisna türüne göre filtrele', 'Filter by exception')
k('filterResolvedDesc', 'Çözülme durumuna göre filtrele', 'Filter by resolved status')
k('colUser', 'Kullanıcı', 'User')
k('colIp', 'IP', 'IP')
k('colLocation', 'Konum', 'Location')
k('colPlatform', 'Platform', 'Platform')
k('colRelease', 'Sürüm', 'Release')
k('colStart', 'Başlangıç', 'Started')
k('colDuration', 'Süre', 'Duration')
k('colEvent', 'Olay', 'Event')

# ---------------- session detail / player ----------------
k('sessionLoading', 'Oturum yükleniyor', 'Loading session')
k('sessionLoadFailed', 'Oturum alınamadı: {error}', 'Could not load the session: {error}', {'error': 'String'})
k('sessionReplay', 'Kayıt', 'Replay')
k('sessionFramesAndDuration', '{frames} kare · {duration}', '{frames} frames · {duration}', {'frames': 'int', 'duration': 'String'})
k('sessionTimeline', 'Zaman çizgisi', 'Timeline')
k('sessionItemCount', '{count} öğe', '{count, plural, =1{1 item} other{{count} items}}', {'count': 'int'})
k('sessionNoItems', 'Öğe yok.', 'No items.')
k('sessionHeader', 'Oturum {id}', 'Session {id}', {'id': 'String'})
k('sessionFullscreenTitle', 'Oturum {id} · {user}', 'Session {id} · {user}', {'id': 'String', 'user': 'String'})
k('replayNoFrames', 'Bu oturumda kare yok (SightpaneReplay sarılmamış ya da kayıt kapalı).', 'This session has no frames (SightpaneReplay is not wrapped, or replay is off).')
k('replayNoFramesGeneric', 'Bu oturumda kare yok (oturum kaydı kapalı veya gönderilmemiş).', 'This session has no replay frames recorded (replay is disabled or not sent).')
k('replayDomPlayerTitle', 'DOM Kaydı ({count} olay)', 'DOM Replay ({count} events)', {'count': 'int'})
k('replayPosition', '{position} / {total} sn', '{position} / {total}s', {'position': 'String', 'total': 'String'})
k('replayBuffer', 'önbellek {done}/{total}', 'buffer {done}/{total}', {'done': 'int', 'total': 'int'})
k('replayFullscreenHint', 'ESC kapatır · boşluk oynat/duraklat', 'ESC closes · space plays/pauses')
k('itemIssueLink', 'Hata grubu #{id}', 'Error group #{id}', {'id': 'int'})
k('itemRoute', 'rota {route}', 'route {route}', {'route': 'String'})
k('itemBreadcrumbsBefore', 'Hata öncesi adımlar', 'Steps before the error')

# ---------------- client & device info ----------------
k('sessionClientInfo', 'İstemci ve Ortam Bilgileri', 'Client & Environment Info')
k('clientPlatform', 'Platform', 'Platform')
k('clientPlatformDesktop', 'Masaüstü (Desktop)', 'Desktop')
k('clientPlatformWeb', 'Web', 'Web')
k('clientPlatformMobile', 'Mobil', 'Mobile')
k('clientOS', 'İşletim Sistemi', 'Operating System')
k('clientOsVersion', 'OS Sürümü', 'OS Version')
k('clientKernel', 'Çekirdek (Kernel)', 'Kernel')
k('clientKernelVersion', 'Çekirdek Sürümü', 'Kernel Version')
k('clientBrowser', 'Tarayıcı', 'Browser')
k('clientBrowserVersion', 'Tarayıcı Sürümü', 'Browser Version')
k('clientArch', 'Mimari', 'Architecture')
k('clientCores', 'CPU Çekirdekleri', 'CPU Cores')
k('clientScreen', 'Ekran Çözünürlüğü', 'Screen Resolution')
k('clientLocale', 'Dil / Yerel Ayar', 'Locale')
k('clientLocation', 'Konum', 'Location')
k('clientCoordinates', 'Koordinatlar', 'Coordinates')
k('clientSdk', 'SDK', 'SDK')

# ---------------- events ----------------
k('eventsTitle', 'Olaylar', 'Events')
k('eventsSubtitle', 'son 30 gün', 'last 30 days')
k('eventsTypes', 'Olay türleri', 'Event types')
k('eventsLoadFailed', 'Olaylar alınamadı: {error}', 'Could not load events: {error}', {'error': 'String'})
k('eventsEmpty', 'Olay yok. SDK’da Hog.capture(’olay’) çağırın.', 'No events. Call Hog.capture(’event’) in the SDK.')
k('colTotal', 'Toplam', 'Total')

# ---------------- settings ----------------
k('settingsTitle', 'Ayarlar', 'Settings')
k('settingsProjectLoadFailed', 'Proje alınamadı: {error}', 'Could not load the project: {error}', {'error': 'String'})
k('settingsProject', 'Proje', 'Project')
k('settingsMemberReadOnly', 'üye · yalnızca görüntüleme', 'member · read only')
k('settingsProjectNameLabel', 'Ad', 'Name')
k('settingsSaved', 'Kaydedildi', 'Saved')
k('settingsRotateKey', 'Anahtarı döndür', 'Rotate the key')
k('settingsRotateKeyBody', 'Eski anahtarla gönderen uygulamalar reddedilecek. Yeni anahtarı SDK yapılandırmasına işlemeniz gerekir.', 'Apps still sending the old key will be rejected. You must put the new key into the SDK configuration.')
k('settingsRotate', 'Döndür', 'Rotate')
k('settingsSdkSetup', 'SDK kurulumu', 'SDK setup')
k('settingsSdkSetupNote', 'endpoint ve apiKey init sırasında verilir', 'endpoint and apiKey are passed at init')
k('settingsMembers', 'Üyeler', 'Members')
k('settingsMemberRemoved', 'Üye çıkarıldı', 'Member removed')
k('settingsMemberAdded', 'Üye eklendi', 'Member added')
k('settingsAddMember', 'Üye ekle', 'Add member')
k('settingsMemberEmailHint', 'uye@sirket.com (kayıtlı olmalı)', 'member@company.com (must be registered)')

# ---------------- alerts & notifications ----------------
k('settingsAlertsTitle', 'Uyarılar ve Bildirimler', 'Alerts & Notifications')
k('settingsAlertChannels', 'Bildirim Kanalları', 'Notification Channels')
k('settingsAlertChannelsEmpty', 'Henüz bildirim kanalı eklenmedi.', 'No notification channels added yet.')
k('settingsAlertChannelAdd', 'Kanal ekle', 'Add channel')
k('settingsAlertChannelName', 'Kanal adı', 'Channel name')
k('settingsAlertChannelKind', 'Kanal türü', 'Channel kind')
k('settingsAlertChannelTarget', 'Hedef', 'Target')
k('settingsAlertChannelTargetHint', 'E-posta, Slack veya Webhook URL', 'Email, Slack, or Webhook URL')
k('settingsAlertChannelSecret', 'Gizli anahtar (Secret)', 'Secret key')
k('settingsAlertChannelSecretHint', 'Webhook için isteğe bağlı HMAC anahtarı', 'Optional HMAC secret for webhooks')
k('settingsAlertChannelTest', 'Test gönder', 'Send test')
k('settingsAlertChannelTestSuccess', 'Test bildirimi başarıyla gönderildi.', 'Test notification sent successfully.')
k('settingsAlertChannelDeleteConfirm', 'Bu bildirim kanalını silmek istediğinize emin misiniz?', 'Are you sure you want to delete this notification channel?')
k('settingsAlertRules', 'Uyarı Kuralları', 'Alert Rules')
k('settingsAlertRulesEmpty', 'Henüz uyarı kuralı eklenmedi.', 'No alert rules added yet.')
k('settingsAlertRuleAdd', 'Kural ekle', 'Add rule')
k('settingsAlertRuleName', 'Kural adı', 'Rule name')
k('settingsAlertRuleKind', 'Olay türü', 'Event kind')
k('settingsAlertRuleKindNewIssue', 'Yeni hata', 'New issue')
k('settingsAlertRuleKindRegression', 'Yeniden oluşan hata (Regresyon)', 'Regressed issue')
k('settingsAlertRuleKindRateSpike', 'Hata oranı artışı (Spike)', 'Error rate spike')
k('settingsAlertRuleKindCrashFree', 'Çökmesiz oturum düşüşü', 'Crash-free rate drop')
k('settingsAlertRuleChannels', 'Kanallar', 'Channels')
k('settingsAlertRuleChannelsSelectHint', 'En az bir kanal seçin', 'Select at least one channel')
k('settingsAlertRuleThreshold', 'Eşik değeri', 'Threshold')
k('settingsAlertRuleWindow', 'Zaman aralığı (dakika)', 'Time window (minutes)')
k('settingsAlertRuleEnabled', 'Etkin', 'Enabled')
k('settingsAlertRuleDeleteConfirm', 'Bu uyarı kuralını silmek istediğinize emin misiniz?', 'Are you sure you want to delete this alert rule?')

k('settingsDangerZone', 'Tehlikeli bölge', 'Danger zone')
k('settingsDeleteBody', 'Projeyi ve tüm oturum, hata, kare verisini kalıcı olarak siler.', 'Permanently deletes the project and all its session, error and frame data.')
k('settingsDeleteProject', 'Projeyi sil', 'Delete project')
k('settingsDeleteConfirmTitle', '"{name}" silinsin mi?', 'Delete "{name}"?', {'name': 'String'})
k('settingsDeleteConfirmBody', 'Bu işlem geri alınamaz.', 'This cannot be undone.')

# ---------------- performance ----------------
k('performanceTitle', 'Performans', 'Performance')
k('performanceSubtitle', '{count} işlem izleniyor', '{count} operations tracked', {'count': 'int'})
k('performanceEmpty', 'Henüz performans verisi yok.', 'No performance data yet.')
k('performanceLoadFailed', 'Performans verisi yüklenemedi: {error}', 'Failed to load performance data: {error}', {'error': 'String'})
k('colOperation', 'İşlem Türü', 'Operation')
k('colTransaction', 'İşlem Adı', 'Transaction')
k('colP50', 'p50', 'p50')
k('colP95', 'p95', 'p95')
k('colAvg', 'Ort.', 'Avg')
k('colCalls', 'Çağrı', 'Calls')
k('colErrorRate', 'Hata %', 'Error %')
k('colAction', 'İşlem', 'Action')
k('performanceSlowestSamples', 'En Yavaş Örnekler', 'Slowest Samples')
k('performanceViewReplay', 'Kaydı Aç', 'View Replay')
k('performanceDays7', 'Son 7 Gün', 'Last 7 Days')
k('performanceDays14', 'Son 14 Gün', 'Last 14 Days')
k('performanceDays30', 'Son 30 Gün', 'Last 30 Days')

# ---------------- users ----------------
k('usersTitle', 'Kullanıcılar', 'Users')
k('usersSubtitle', '{count} kullanıcı', '{count, plural, =1{1 user} other{{count} users}}', {'count': 'int'})
k('usersSearchPlaceholder', 'Kullanıcı veya e-posta ara...', 'Search user or email...')
k('usersLoadFailed', 'Kullanıcılar alınamadı: {error}', 'Could not load users: {error}', {'error': 'String'})
k('usersEmpty', 'Kullanıcı bulunamadı.', 'No users found.')
k('kpiTotalUsers', 'Toplam Kullanıcı', 'Total Users')
k('kpiActiveUsers', 'Aktif Kullanıcı (Dönem)', 'Active Users (Period)')
k('kpiAvgDuration', 'Ortalama Süre', 'Avg Session Duration')
k('kpiSessionsPerUser', 'Kullanıcı Başı Oturum', 'Sessions / User')
k('chartActiveUsers', 'Günlük Aktif Kullanıcılar (DAU)', 'Daily Active Users (DAU)')
k('chartActiveUsersSub', 'mavi aktif kullanıcılar · kırmızı hatalı kullanıcılar', 'blue active users · red error-affected users')
k('colAvgDuration', 'Ort. Süre', 'Avg Duration')
k('colFirstSeen', 'İlk Görülme', 'First Seen')
k('colLastSeen', 'Son Görülme', 'Last Seen')
k('userDetailTitle', 'Kullanıcı Detayları', 'User Details')
k('actionViewSessions', 'Oturumları Gör', 'View Sessions')
k('actionExportData', 'Veriyi İndir (JSON)', 'Export Data (JSON)')
k('actionDeleteData', 'Kullanıcı Verisini Sil', 'Delete User Data')
k('userDeleteConfirm', 'Bu kullanıcının tüm oturum ve hata kayıtları silinsin mi?', 'Delete all sessions and error records for this user?')
k('userDeleteSuccess', 'Kullanıcı verisi başarıyla silindi.', 'User data deleted successfully.')
k('userCustomProps', 'Özel Nitelikler', 'Custom Attributes')
k('usersVisitorMapTitle', 'Ziyaretçi Haritası', 'Visitor Map')
k('usersVisitorMapSub', 'GeoIP konumlarına göre ziyaretçi coğrafi dağılımı', 'Geographic distribution of visitors based on GeoIP')
k('usersMapNoData', 'Bu dönem için konum verisi kaydedilmemiş.', 'No location data recorded for this period.')
k('usersMapVisitorsCount', '{count} ziyaretçi', '{count, plural, =1{1 visitor} other{{count} visitors}}', {'count': 'int'})
k('usersMapLocationsCount', '{count} konum', '{count, plural, =1{1 location} other{{count} locations}}', {'count': 'int'})
k('usersMapResetView', 'Görünümü Sıfırla', 'Reset View')
k('usersMapZoomIn', 'Yakınlaştır', 'Zoom In')
k('usersMapZoomOut', 'Uzaklaştır', 'Zoom Out')

# ---------------- funnels ----------------
k('navFunnels', 'Huniler', 'Funnels')
k('funnelsTitle', 'Dönüşüm Hunileri', 'Conversion Funnels')
k('funnelsSubtitle', '{count} huni tanımlı', '{count, plural, =1{1 funnel defined} other{{count} funnels defined}}', {'count': 'int'})
k('funnelCreate', 'Huni Oluştur', 'Create Funnel')
k('funnelName', 'Huni Adı', 'Funnel Name')
k('funnelDescription', 'Açıklama', 'Description')
k('funnelSteps', 'Huni Adımları', 'Funnel Steps')
k('funnelStepAdd', 'Adım Ekle', 'Add Step')
k('funnelStepEvent', 'Olay Adı', 'Event Name')
k('funnelWindow', 'Dönüşüm Penceresi', 'Conversion Window')
k('funnelWindow1d', '1 Gün', '1 Day')
k('funnelWindow7d', '7 Gün', '7 Days')
k('funnelWindow14d', '14 Gün', '14 Days')
k('funnelWindow30d', '30 Gün', '30 Days')
k('funnelsEmpty', 'Henüz tanımlanmış bir huni yok.', 'No conversion funnels defined yet.')
k('funnelsEmptyHint', 'Kullanıcı yolculuklarındaki dönüşüm ve terk oranlarını izlemek için ilk huninizi oluşturun.', 'Create your first funnel to track conversion and drop-off rates along user journeys.')
k('funnelOverallConversion', 'Genel Dönüşüm Oranı', 'Overall Conversion Rate')
k('funnelCompletedSessions', 'Tamamlayan Oturum', 'Completed Sessions')
k('funnelTotalSessions', 'Başlayan Oturum', 'Started Sessions')
k('funnelMedianTime', 'Medyan Dönüşüm Süresi', 'Median Conversion Time')
k('funnelStepConversion', 'Adım Dönüşümü', 'Step Conversion')
k('funnelDropOff', 'Terk Eden', 'Drop-off')
k('funnelWatchReplays', 'Terk Eden Kayıtları İzle ({count})', 'Watch Drop-off Replays ({count})', {'count': 'int'})
k('funnelDeleteConfirm', 'Bu huniyi silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this funnel?')
k('funnelDeleted', 'Huni silindi.', 'Funnel deleted.')
k('funnelCreated', 'Huni oluşturuldu.', 'Funnel created.')
k('funnelUpdated', 'Huni güncellendi.', 'Funnel updated.')
k('funnelStepMin', 'En az 2 adım gereklidir.', 'At least 2 steps are required.')

# ---------------- cohorts & retention ----------------
k('navRetention', 'Elde Tutma (Retention)', 'Retention')
k('navCohorts', 'Kohortlar', 'Cohorts')
k('retentionTitle', 'Kullanıcı Elde Tutma Matrisi', 'User Retention Matrix')
k('retentionSubtitle', 'Kullanıcıların zaman içinde uygulamanıza geri dönüş oranlarını kohort bazında analiz edin.', 'Analyze how cohorts of users return to your application over time.')
k('retentionPeriodDay', 'Günlük', 'Daily')
k('retentionPeriodWeek', 'Haftalık', 'Weekly')
k('retentionTargetEvent', 'İlk Olay (Hedef)', 'Target Event (Initial)')
k('retentionReturnEvent', 'Dönüş Olayı', 'Return Event')
k('retentionAllUsers', 'Tüm Kullanıcılar', 'All Users')
k('retentionCohortFilter', 'Kohort Filtresi', 'Cohort Filter')
k('retentionHeatmapTitle', 'Elde Tutma Isı Haritası', 'Retention Heatmap')
k('retentionBucket', 'Kohort Başlangıcı', 'Cohort Date')
k('retentionUsers', 'Kullanıcı', 'Users')
k('retentionPeriodN', '{unit} {index}', '{unit} {index}', {'unit': 'String', 'index': 'int'})
k('retentionEmpty', 'Seçilen aralıkta elde tutma verisi bulunamadı.', 'No retention data found for the selected range.')
k('cohortsTitle', 'Davranışsal Kohortlar', 'Behavioral Cohorts')
k('cohortsSubtitle', 'Kullanıcıları belirli davranış ve özelliklere göre segmentlere ayırın.', 'Segment users by behavioral patterns and event frequency.')
k('newCohort', 'Yeni Kohort', 'New Cohort')
k('cohortName', 'Kohort Adı', 'Cohort Name')
k('cohortDescription', 'Açıklama', 'Description')
k('cohortRules', 'Dinamik Kurallar', 'Dynamic Rules')
k('cohortDynamic', 'Dinamik', 'Dynamic')
k('cohortStatic', 'Statik', 'Static')
k('cohortMemberCount', 'Üye Sayısı', 'Member Count')
k('refreshCohort', 'Kohortu Güncelle', 'Refresh Cohort')
k('cohortRefreshed', 'Kohort üyeleri güncellendi.', 'Cohort members refreshed.')
k('cohortCreated', 'Kohort oluşturuldu.', 'Cohort created.')
k('cohortDeleted', 'Kohort silindi.', 'Cohort deleted.')
k('cohortDeleteConfirm', 'Bu kohortu silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this cohort?')
k('cohortEmpty', 'Henüz tanımlanmış bir kohort yok.', 'No cohorts defined yet.')
k('cohortEmptyHint', 'Kullanıcıları davranışlarına göre gruplandırmak için ilk kohortunuzu oluşturun.', 'Create your first cohort to group users by their actions.')
k('cohortAddRule', 'Kural Ekle', 'Add Rule')
k('cohortEventName', 'Olay Adı', 'Event Name')
k('cohortOperator', 'İşleç', 'Operator')
k('cohortValue', 'Değer', 'Value')
k('cohortWindowDays', 'Zaman Penceresi (Gün)', 'Window (Days)')

# ---------------- user paths / flows ----------------
k('navPaths', 'Kullanıcı Yolları (Paths)', 'User Paths')
k('pathsTitle', 'Kullanıcı Yolculuk Akışları', 'User Journey Flows')
k('pathsSubtitle', 'Kullanıcıların ekranlar ve olaylar arasındaki geçişlerini Sankey akış şemasıyla inceleyin.', 'Explore user transitions across screens and events using Sankey journey diagrams.')
k('pathsForward', 'İleri (Başlangıçtan)', 'Forward (From Start)')
k('pathsReverse', 'Geriye Doğru (Hedefe)', 'Reverse (Leading to Target)')
k('pathsRootEvent', 'Kök Olay / Ekran', 'Root Event / Screen')
k('pathsRootPlaceholder', 'Örn: route:/login veya error', 'e.g. route:/login or error')
k('pathsStepLimit', 'Adım Derinliği', 'Step Depth')
k('pathsExclude', 'Hariç Tutulanlar', 'Exclude Events')
k('pathsExcludePlaceholder', 'Örn: heartbeat, pointer', 'e.g. heartbeat, pointer')
k('pathsThreshold', 'Eşik (%)', 'Threshold (%)')
k('pathsDiagramTitle', 'Geçiş Akış Şeması (Sankey)', 'Transition Flow Diagram (Sankey)')
k('pathsEmpty', 'Seçilen kriterlere uygun kullanıcı yolu bulunamadı.', 'No user paths found matching the selected criteria.')
k('pathsSampleSessions', 'Örnek Oturumlar ({count})', 'Sample Sessions ({count})', {'count': 'int'})
k('pathsReplaysModalTitle', 'Yolculuk Oturum Kayıtları', 'Journey Session Replays')
k('pathsExit', 'Terk (Exit)', 'Exit')

# ---------------- feature flags ----------------
k('navFeatureFlags', 'Özellik Bayrakları (Flags)', 'Feature Flags')
k('flagsTitle', 'Özellik Bayrakları & Uzaktan Yapılandırma', 'Feature Flags & Remote Config')
k('flagsSubtitle', 'Kod yayınlamadan özellikleri anında açıp kapatın, kademeli dağıtım (canary) ve kural hedeflemesi yapın.', 'Toggle features instantly without deploying code, manage graduated rollouts and target user segments.')
k('flagsNew', 'Yeni Bayrak', 'New Feature Flag')
k('flagsKey', 'Bayrak Anahtarı (Key)', 'Flag Key')
k('flagsKeyHint', 'Örn: new_checkout_flow', 'e.g. new_checkout_flow')
k('flagsName', 'Ad', 'Name')
k('flagsDesc', 'Açıklama', 'Description')
k('flagsRollout', 'Kademeli Dağıtım (%)', 'Rollout Percentage (%)')
k('flagsActive', 'Aktif', 'Active')
k('flagsDisabled', 'Devre Dışı', 'Disabled')
k('flagsVariants', 'Çoklu Varyantlar (Multivariant)', 'Variants')
k('flagsFilters', 'Hedefleme Kuralları', 'Targeting Rules')
k('flagsAddFilter', 'Kural Ekle', 'Add Rule')
k('flagsAddVariant', 'Varyant Ekle', 'Add Variant')
k('flagsTestTitle', 'Canlı Değerlendirme Testi', 'Live Evaluation Preview')
k('flagsTestDistinctId', 'Kullanıcı ID (distinct_id)', 'Distinct User ID')
k('flagsTestResult', 'Değerlendirme Sonucu', 'Evaluation Result')
k('flagsDeleted', 'Bayrak silindi.', 'Feature flag deleted.')
k('flagsSaved', 'Bayrak kaydedildi.', 'Feature flag saved.')
k('flagsEmpty', 'Henüz bir özellik bayrağı oluşturulmadı.', 'No feature flags created yet.')

# ---------------- experiments ----------------
k('navExperiments', 'Deneyler (A/B Testi)', 'Experiments')
k('experimentsTitle', 'Deneyler (A/B Testi)', 'Experiments (A/B Testing)')
k('experimentsDesc', 'Dönüşüm oranlarını artırmak ve hipotezleri istatistiksel güvenle doğrulamak için kontrollü A/B testleri çalıştırın.', 'Run controlled A/B tests to improve conversion and validate hypotheses with statistical significance.')
k('experimentsNew', 'Yeni Deney', 'New Experiment')
k('experimentsRunning', 'Devam Eden', 'Running')
k('experimentsDraft', 'Taslak', 'Draft')
k('experimentsConcluded', 'Tamamlandı', 'Concluded')
k('experimentsTargetMetric', 'Birincil Hedef Olayı', 'Primary Metric Event')
k('experimentsFlagKey', 'Bağlı Özellik Bayrağı', 'Linked Feature Flag')
k('experimentsSampleSize', 'Hedef Örneklem Boyutu', 'Target Sample Size')
k('experimentsSignificant', 'İstatistiksel Olarak Anlamlı', 'Statistically Significant')
k('experimentsNeedsData', 'Daha Fazla Veri Gerekiyor', 'Needs More Data')
k('experimentsDeclareWinner', 'Kazananı İlan Et', 'Declare Winner')
k('experimentsRolloutWinner', 'Kazananı %100 Dağıt', 'Roll Out Winner to 100%')
k('experimentsWinnerDeclared', 'Kazanan ilan edildi ve özellik bayrağı %100 güncellendi.', 'Winner declared and feature flag rolled out to 100%.')
k('experimentsConversionRate', 'Dönüşüm Oranı', 'Conversion Rate')
k('experimentsParticipants', 'Katılımcılar', 'Participants')
k('experimentsConversions', 'Dönüşümler', 'Conversions')
k('experimentsRelativeLift', 'Göreceli Artış', 'Relative Lift')
k('experimentsChanceToWin', 'Kazanma Şansı', 'Chance to Win')
k('experimentsConfidenceInterval', '%95 Güven Aralığı', '95% Confidence Interval')
k('experimentsEmpty', 'Henüz bir A/B deneyi oluşturulmadı.', 'No A/B experiments created yet.')
k('experimentsDeleteConfirm', 'Bu deneyi silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this experiment?')

# ---------------- surveys ----------------
k('navSurveys', 'Anketler & Geri Bildirim', 'Surveys & Feedback')
k('surveysTitle', 'Kullanıcı Anketleri & Geri Bildirim', 'In-App Surveys & User Feedback')
k('surveysDesc', 'NPS, CSAT ve serbest metin anketleriyle doğrudan oturum kayıtlarına bağlı kullanıcı geri bildirimleri toplayın.', 'Collect NPS, CSAT, and open text feedback directly linked to user session replays.')
k('surveysNew', 'Yeni Anket', 'New Survey')
k('surveysType', 'Anket Türü', 'Survey Type')
k('surveysQuestion', 'Soru', 'Question')
k('surveysResponses', 'Yanıtlar', 'Responses')
k('surveysNpsScore', 'Net Promoter Score (NPS)', 'Net Promoter Score (NPS)')
k('surveysCsatScore', 'Müşteri Memnuniyeti (CSAT)', 'Customer Satisfaction (CSAT)')
k('surveysPromoters', 'Destekçiler (9-10)', 'Promoters (9-10)')
k('surveysPassives', 'Pasifler (7-8)', 'Passives (7-8)')
k('surveysDetractors', 'Kötüleyenler (0-6)', 'Detractors (0-6)')
k('surveysWatchReplay', 'Oturumu İzle', 'Watch Replay')
k('surveysNoReplay', 'Kayıt Yok', 'No Replay')
k('surveysEmpty', 'Henüz bir anket oluşturulmadı.', 'No surveys created yet.')
k('surveysDeleteConfirm', 'Bu anketi silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this survey?')
k('surveysDeleted', 'Anket silindi.', 'Survey deleted.')
k('surveysSaved', 'Anket kaydedildi.', 'Survey saved.')
k('surveysScoreDistribution', 'Puan Dağılımı', 'Score Distribution')
k('surveysIndividualResponses', 'Bireysel Yanıtlar', 'Individual Responses')
k('surveysActive', 'Aktif', 'Active')
k('surveysInactive', 'Pasif', 'Inactive')

# ---------------- crons ----------------
k('navCrons', 'Cron & Heartbeat', 'Crons & Heartbeats')
k('cronsTitle', 'Cron İşleri & Heartbeat İzleme', 'Cron Jobs & Heartbeat Monitoring')
k('cronsDesc', 'Arka plan işlerinizi, zamanlanmış görevleri ve worker heartbeat sinyallerini izleyin, gecikmelerde anında uyarı alın.', 'Monitor background jobs, scheduled tasks, and worker heartbeats with instant alerts on missed deadlines.')
k('cronsNew', 'Yeni Cron İzleyici', 'New Cron Monitor')
k('cronsSchedule', 'Zamanlama (Crontab)', 'Schedule (Crontab)')
k('cronsTimezone', 'Zaman Dilimi', 'Timezone')
k('cronsGracePeriod', 'Tolerans Süresi (dk)', 'Grace Period (min)')
k('cronsMaxRuntime', 'Maks Çalışma Süresi (dk)', 'Max Runtime (min)')
k('cronsNextExpected', 'Sonraki Beklenen', 'Next Expected')
k('cronsLastCheckin', 'Son Check-in', 'Last Check-in')
k('cronsStatusOk', 'Çalışıyor', 'Healthy')
k('cronsStatusInProgress', 'İşlemde', 'In Progress')
k('cronsStatusMissed', 'Kaçırıldı', 'Missed')
k('cronsStatusError', 'Hata Aldı', 'Failed')
k('cronsTimeline24h', '24 Saatlik Durum Geçmişi', '24-Hour Status Timeline')
k('cronsIntegrationSnippets', 'Entegrasyon Kodları', 'Integration Code Snippets')
k('cronsHistory', 'Check-in Geçmişi', 'Check-in History')
k('cronsEmpty', 'Henüz bir cron izleyicisi eklenmedi.', 'No cron monitors created yet.')
k('cronsDeleteConfirm', 'Bu cron izleyicisini silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this cron monitor?')
k('cronsDeleted', 'Cron izleyicisi silindi.', 'Cron monitor deleted.')
k('cronsSaved', 'Cron izleyicisi kaydedildi.', 'Cron monitor saved.')
k('cronsSlug', 'Slug / Tanımlayıcı', 'Slug / Identifier')
k('cronsName', 'İzleyici Adı', 'Monitor Name')
k('cronsDuration', 'Süre', 'Duration')
k('cronsMessage', 'Mesaj', 'Message')
k('cronsTotal', 'Toplam İzleyici', 'Total Monitors')

# ---------------- uptime ----------------
k('navUptime', 'Uptime & Sentetik', 'Uptime & Synthetics')
k('uptimeTitle', 'Uptime & Sentetik İzleme', 'Uptime & Synthetic Monitoring')
k('uptimeDesc', 'Uç nokta erişilebilirliğini, yanıt sürelerini ve SSL sertifika geçerliliğini aktif olarak izleyin.', 'Actively monitor endpoint availability, response latency, and SSL certificate expiration.')
k('uptimeNew', 'Yeni İzleyici', 'New Monitor')
k('uptimeEdit', 'İzleyiciyi Düzenle', 'Edit Monitor')
k('uptimeEmpty', 'Henüz bir uptime izleyicisi eklenmedi.', 'No uptime monitors created yet.')
k('uptimeEmptyDesc', 'API ve web uygulamalarınız için sentetik sağlık kontrolleri oluşturarak kesintileri anında tespit edin.', 'Create synthetic health checks for your APIs and web apps to catch downtime instantly.')
k('uptimeTotal', 'Toplam İzleyici', 'Total Monitors')
k('uptimeSLA', 'SLA Oranı', 'SLA Uptime')
k('uptimeUp', 'Çalışıyor', 'Operational')
k('uptimeDegraded', 'Kısmi Kesinti', 'Degraded')
k('uptimeDown', 'Kesintide', 'Down')
k('uptimeCheckNow', 'Şimdi Kontrol Et', 'Check Now')
k('uptimeChecking', 'Kontrol ediliyor...', 'Checking...')
k('uptimeCheckedSuccess', 'Kontrol başarıyla tamamlandı.', 'Check completed successfully.')
k('uptimeCheckedFailed', 'Kontrol başarısız oldu.', 'Check failed.')
k('uptimeDeleteConfirm', 'Bu uptime izleyicisini silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this uptime monitor?')
k('uptimeDeleted', 'İzleyici silindi.', 'Monitor deleted.')
k('uptimeSaved', 'İzleyici kaydedildi.', 'Monitor saved.')
k('uptimeName', 'İzleyici Adı', 'Monitor Name')
k('uptimeURL', 'Hedef URL', 'Target URL')
k('uptimeMethod', 'HTTP Yöntemi', 'HTTP Method')
k('uptimeInterval', 'Kontrol Aralığı', 'Check Interval')
k('uptimeTimeout', 'Zaman Aşımı', 'Timeout')
k('uptimeExpectedStatus', 'Beklenen Durum Kodu', 'Expected Status Code')
k('uptimeSSLCheck', 'SSL/TLS Sertifika Kontrolü', 'SSL/TLS Certificate Check')
k('uptimeSSLIssuer', 'Sertifika Sağlayıcı', 'Certificate Issuer')
k('uptimeSSLExpires', 'SSL Süresi', 'SSL Expiration')
k('uptimeSSLValid', 'Geçerli', 'Valid')
k('uptimeSSLExpired', 'Süresi Doldu', 'Expired')
k('uptimeSSLDaysLeft', '{days} gün kaldı', '{days, plural, =1{1 day remaining} other{{days} days remaining}}', {'days': 'int'})
k('uptimeTimeline90d', '90 Günlük Erişilebilirlik Geçmişi', '90-Day Availability History')
k('uptimeResponseTime', 'Yanıt Süresi', 'Response Time')
k('uptimeAvgResponseTime', 'Ort. Yanıt Süresi', 'Avg Response Time')
k('uptimeRecentChecks', 'Son Kontroller', 'Recent Checks')
k('uptimeStatusCode', 'Durum Kodu', 'Status Code')
k('uptimeCheckedAt', 'Kontrol Zamanı', 'Checked At')
k('uptimeErrorMessage', 'Hata Detayı', 'Error Detail')
k('uptimeStatus', 'Durum', 'Status')
k('uptimeLastChecked', 'Son Kontrol', 'Last Checked')

# ---------------- metric alerts & anomaly detection ----------------
k('navAlerts', 'Metrik Uyarıları', 'Metric Alerts')
k('alertsTitle', 'Metrik Uyarıları & Anomali Tespiti', 'Metric Alerts & Anomaly Detection')
k('alertsSubtitle', 'Metrik eşiklerini, anomali artışlarını ve olay durumlarını izleyin.', 'Monitor metric thresholds, anomaly spikes, and incident states.')
k('alertsTabRules', 'Kurallar', 'Rules')
k('alertsTabIncidents', 'Olay Geçmişi', 'Incident History')
k('alertsNewRule', 'Yeni Kural', 'New Rule')
k('alertsEditRule', 'Kuralı Düzenle', 'Edit Rule')
k('alertsRuleName', 'Kural Adı', 'Rule Name')
k('alertsMetricType', 'Metrik Türü', 'Metric Type')
k('alertsComparison', 'Karşılaştırma Operatörü', 'Comparison Operator')
k('alertsCriticalThreshold', 'Kritik Eşik', 'Critical Threshold')
k('alertsWarningThreshold', 'Uyarı Eşiği (İsteğe bağlı)', 'Warning Threshold (Optional)')
k('alertsWindowMinutes', 'Değerlendirme Penceresi', 'Evaluation Window')
k('alertsTargetFilter', 'Hedef Filtresi (örn: route:/checkout)', 'Target Filter (e.g. route:/checkout)')
k('alertsChannels', 'Bildirim Kanalları', 'Notification Channels')
k('alertsSaveRule', 'Kuralı Kaydet', 'Save Rule')
k('alertsRuleSaved', 'Kural başarıyla kaydedildi.', 'Rule saved successfully.')
k('alertsDeleteConfirm', 'Bu metrik uyarı kuralını silmek istediğinize emin misiniz?', 'Are you sure you want to delete this metric alert rule?')
k('alertsDeleted', 'Kural silindi.', 'Rule deleted.')
k('alertsStatusFiring', 'Tetiklendi', 'Firing')
k('alertsStatusWarning', 'Uyarı', 'Warning')
k('alertsStatusOk', 'Normal', 'OK')
k('alertsStatusResolved', 'Çözüldü', 'Resolved')
k('alertsPreviewChart', 'Geçmiş Metrik & Eşik Önizlemesi (Son 7 Gün)', 'Historical Metric & Threshold Preview (Last 7 Days)')
k('alertsPreviewSub', 'Geçmiş verilere göre kuralın ne zaman tetikleneceğini görselleştirin.', 'Visualize when the rule would have triggered based on historical data.')
k('alertsEmptyRules', 'Henüz metrik kuralı tanımlanmadı.', 'No metric rules defined yet.')
k('alertsEmptyIncidents', 'Kayıtlı olay bulunmuyor.', 'No recorded incidents.')
k('alertsPeakValue', 'Zirve Değer', 'Peak Value')
k('alertsDuration', 'Süre', 'Duration')
k('alertsTriggerNow', 'Şimdi Test Et', 'Test Now')
k('alertsOperatorGt', 'Büyüktür (>)', 'Greater than (>)')
k('alertsOperatorGte', 'Büyük veya eşittir (>=)', 'Greater than or equal (>=)')
k('alertsOperatorLt', 'Küçüktür (<)', 'Less than (<)')
k('alertsOperatorSpike', 'Anomali Artışı (x Kat)', 'Anomaly Spike (x Multiplier)')
k('alertsMetricErrorCount', 'Hata Sayısı', 'Error Count')
k('alertsMetricErrorRate', 'Hata Oranı (%)', 'Error Rate (%)')
k('alertsMetricP95Duration', 'p95 Yanıt Süresi (ms)', 'p95 Latency (ms)')
k('alertsMetricCrashCount', 'Çökme Sayısı', 'Crash Count')

# ---------------- distributed tracing & spans ----------------
k('navTraces', 'Dağıtık İzler (Traces)', 'Distributed Traces')
k('tracesTitle', 'Dağıtık İzleme & Waterfall', 'Distributed Traces & Spans')
k('tracesSubtitle', 'Mikroservisler ve veritabanı sorguları arasındaki gecikme ve N+1 sorunlarını analiz edin.', 'Trace end-to-end distributed requests across microservices, databases, and identify N+1 bottlenecks.')
k('tracesEmpty', 'Henüz bir iz (trace) kaydı bulunamadı.', 'No traces found for the selected filters.')
k('tracesFilterService', 'Servis', 'Service')
k('tracesFilterMinDuration', 'Min Süre (ms)', 'Min Duration (ms)')
k('tracesSearchPlaceholder', 'İz ID veya kök işlem ara...', 'Search trace ID or root operation...')
k('traceDetailTitle', 'İz Detayı', 'Trace Detail')
k('traceDetailSpanCount', 'Span Sayısı', 'Total Spans')
k('traceDetailServiceCount', 'Servis Sayısı', 'Total Services')
k('traceDetailDuration', 'Toplam Süre', 'Total Duration')
k('traceSuspectNPlus1', 'Olası N+1 Sorgu Sorunu Tespit Edildi!', 'Suspected N+1 Query Bottleneck Detected!')
k('traceSpanDetails', 'Span Detayı', 'Span Details')
k('traceSqlStatement', 'SQL Sorgusu', 'SQL Statement')
k('traceAttributes', 'Nitelikler & Etiketler', 'Attributes & Tags')
k('traceStatus', 'Durum', 'Status')
k('traceRootSpan', 'Kök İşlem', 'Root Operation')
k('traceTimestamp', 'Başlangıç Zamanı', 'Start Time')
k('performanceViewTrace', 'İz / Trace', 'View Trace')

# ---------------- continuous profiling & flame chart ----------------
k('navProfiling', 'Sürekli Profilleme', 'Profiling')
k('profilingTitle', 'Sürekli CPU Profilleme & Flame Chart', 'Continuous Profiling & Flame Graph')
k('profilingSubtitle', 'Üretim ortamındaki çağrı yığınlarını (call stack) ve en yavaş fonksiyonları interaktif alev grafiği ile analiz edin.', 'Analyze production call stacks, CPU bottlenecks, and slowest functions with interactive flame graphs.')
k('profilingEmpty', 'Henüz bir CPU profil kaydı bulunamadı.', 'No CPU profiles found for the selected filters.')
k('profilingTransaction', 'İşlem (Transaction)', 'Transaction')
k('profilingDuration', 'Toplam Süre', 'Total Duration')
k('profilingCpuTime', 'CPU Süresi', 'CPU Time')
k('profilingThread', 'İş Parçacığı (Thread)', 'Thread')
k('profilingPlatform', 'Platform', 'Platform')
k('profilingSamples', 'Örnek Sayısı (Samples)', 'Samples')
k('profilingFrames', 'Fonksiyon Sayısı (Frames)', 'Frames')
k('profilingSlowFunctions', 'En Yavaş Fonksiyonlar', 'Slowest Functions')
k('profilingFunctionName', 'Fonksiyon Adı', 'Function Name')
k('profilingSelfTime', 'Öz Süre (Self Time)', 'Self Time')
k('profilingTotalTime', 'Toplam Süre (Total Time)', 'Total Time')
k('profilingCallCount', 'Çağrı Sayısı', 'Call Count')
k('profilingDetailTitle', 'Profil & Flame Graph Detayı', 'Profile & Flame Graph Detail')
k('profilingSearchFrame', 'Fonksiyon veya dosya ara...', 'Search function or file...')
k('profilingInvertFlame', 'Aşağıdan Yukarı (Icicle)', 'Invert Graph (Icicle)')
k('profilingResetZoom', 'Yakınlaştırmayı Sıfırla', 'Reset Zoom')
k('profilingSelectedFrame', 'Seçili Fonksiyon Detayı', 'Selected Frame Details')
k('profilingViewProfile', 'Profili Görüntüle', 'View Profile')

# ---------------- custom dashboards & insights ----------------
k('navDashboards', 'Özel Panolar', 'Dashboards')
k('dashboardsTitle', 'Özel Panolar', 'Custom Dashboards')
k('dashboardsSubtitle', 'Takımınız için özelleştirilmiş panolar oluşturun ve metrikleri görselleştirin.', 'Build customized team dashboards and visualize analytical insights.')
k('dashboardCreate', 'Yeni Pano', 'New Dashboard')
k('dashboardEdit', 'Panoyu Düzenle', 'Edit Dashboard')
k('dashboardDelete', 'Panoyu Sil', 'Delete Dashboard')
k('dashboardName', 'Pano Adı', 'Dashboard Name')
k('dashboardNameHint', 'Örn. Yönetici Özeti', 'e.g. Executive Overview')
k('dashboardDescription', 'Açıklama', 'Description')
k('dashboardDescriptionHint', 'Pano amacını kısaca belirtin...', 'Briefly describe dashboard purpose...')
k('dashboardSetDefault', 'Varsayılan Yap', 'Set as Default')
k('dashboardIsDefault', 'Varsayılan Pano', 'Default Dashboard')
k('dashboardEmpty', 'Henüz bir özel pano oluşturulmadı.', 'No custom dashboards created yet.')
k('dashboardTileAdd', 'Görü Ekle', 'Add Insight')
k('dashboardAutoRefresh', 'Otomatik Yenileme', 'Auto Refresh')
k('dashboardRefreshOff', 'Kapalı', 'Off')
k('dashboardDeleteConfirm', 'Bu panoyu silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this dashboard?')
k('dashboardInsightRemove', 'Görüyü Kaldır', 'Remove Insight')
k('dashboardLayoutSave', 'Düzeni Kaydet', 'Save Layout')
k('insightBuilderTitle', 'Görü Oluşturucu', 'Insight Query Builder')
k('insightBuilderSubtitle', 'Olayları, filtreleri ve gruplamaları belirleyerek metrikleri anlık görselleştirin.', 'Define events, filters, and breakdowns to visualize metrics on the fly.')
k('insightName', 'Görü Adı', 'Insight Name')
k('insightNameHint', 'Örn. Günlük Satın Alma Hacmi', 'e.g. Daily Purchase Volume')
k('insightChartType', 'Grafik Türü', 'Chart Type')
k('chartTypeLine', 'Çizgi', 'Line')
k('chartTypeBar', 'Çubuk', 'Bar')
k('chartTypeArea', 'Alan', 'Area')
k('chartTypeNumber', 'Sayısal (KPI)', 'Number (KPI)')
k('chartTypeDonut', 'Halka (Donut)', 'Donut')
k('chartTypeTable', 'Tablo', 'Table')
k('insightDateRange', 'Zaman Aralığı', 'Date Range')
k('insightInterval', 'Zaman Dilimi', 'Interval')
k('intervalHour', 'Saatlik', 'Hourly')
k('intervalDay', 'Günlük', 'Daily')
k('intervalWeek', 'Haftalık', 'Weekly')
k('intervalMonth', 'Aylık', 'Monthly')
k('insightEvents', 'Analiz Olayları', 'Analytics Events')
k('insightEventAdd', 'Olay Ekle', 'Add Event')
k('insightEventName', 'Olay Adı', 'Event Name')
k('insightEventNameHint', 'Örn. purchase, click, pageview', 'e.g. purchase, click, pageview')
k('insightMath', 'Hesaplama (Math)', 'Aggregation (Math)')
k('mathCount', 'Toplam Adet (Count)', 'Total Count')
k('mathUniqueUsers', 'Tekil Kullanıcılar (Unique Users)', 'Unique Users')
k('mathAvg', 'Ortalama (Avg)', 'Average')
k('mathSum', 'Toplam (Sum)', 'Sum')
k('mathMin', 'Minimum (Min)', 'Minimum')
k('mathMax', 'Maksimum (Max)', 'Maximum')
k('mathP90', '90. Yüzdelik (p90)', '90th Percentile')
k('insightProperty', 'Özellik Adı', 'Property Key')
k('insightPropertyHint', 'Örn. amount, duration_ms', 'e.g. amount, duration_ms')
k('insightBreakdown', 'Gruplama (Breakdown)', 'Breakdown by')
k('insightBreakdownNone', 'Gruplama Yok', 'No Breakdown')
k('insightBreakdownPlatform', 'Platform', 'Platform')
k('insightBreakdownBrowser', 'Tarayıcı (Browser)', 'Browser')
k('insightBreakdownCustom', 'Özel Özellik...', 'Custom Property...')
k('insightRunQuery', 'Sorguyu Çalıştır', 'Run Query')
k('insightSave', 'Görüyü Kaydet', 'Save Insight')
k('insightPreview', 'Görselleştirme Önizlemesi', 'Visualization Preview')
k('insightEmptyResults', 'Bu sorgu için gösterilecek veri noktası bulunamadı.', 'No data points found for this query.')
k('insightCached', 'Önbellekten geldi (60s)', 'Cached (60s)')
k('insightDelete', 'Görüyü Sil', 'Delete Insight')
k('insightDeleteConfirm', 'Bu görüyü silmek istediğinizden emin misiniz?', 'Are you sure you want to delete this insight?')
k('dashboardsCount', '{count} pano', '{count, plural, =1{1 dashboard} other{{count} dashboards}}', {'count': 'int'})




def arb(lang, idx):
    out = collections.OrderedDict()
    out['@@locale'] = lang
    for name, (tr, en, ph, desc) in K.items():
        out[name] = (tr, en)[idx]
        meta = {}
        if desc and idx == 0:
            meta['description'] = desc
        if ph:
            meta['placeholders'] = {p: {'type': t} for p, t in ph.items()}
        # Metadata is written in the template language (tr); gen-l10n builds the
        # signatures from there.
        if meta and idx == 0:
            out['@' + name] = meta
    return out

for lang, idx in (('tr', 0), ('en', 1)):
    with open('lib/l10n/app_%s.arb' % lang, 'w', encoding='utf-8') as f:
        json.dump(arb(lang, idx), f, ensure_ascii=False, indent=2)
        f.write('\n')
print('keys:', len(K))
